---
title: "Assignments"
output: 
  html_document:
    includes:
      after_body: _includes/include_footer.html
      in_header: _includes/header_banner.html 
---
<!--
library(knitr)
rmarkdown::render_site("assignments.Rmd")# build website
rmarkdown::render_site()# build website
-->


Over the semester there will be 5 assignments worth 100 points of your 
final grade. Recall you may hand in assignments late but with a 
penalty.^[All assignments must be turned in on time. Late assignments may 
be graded, but the maximum point value will be reduced by 5% for every 
day the assignment is late; however, assignments will not be graded if 
they are turned in after graded assignments are returned to the class. 
If for some reason there is a timing conflict associated with an exam, 
discuss these conflicts with me at least two weeks prior to the 
scheduled date.]



## Assignments
1. Will be posted once assignment is assigned to students
1. Will be posted once assignment is assigned to students
1. Will be posted once assignment is assigned to students
1. Will be posted once assignment is assigned to students
1. Will be posted once assignment is assigned to students



